[tool.poetry]
name = "finance-tracker"
version = "0.1.0"
description = ""
authors = ["Daniel Mejia <danielmejia83@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^3.0.2"
rich = "^15.0.0"
click = "^8.3.3"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
